src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_order = null;

    #[ORM\Column(length: 255)]
    private ?string $quantity = null;

    #[ORM\Column(length: 255)]
    private ?string $price = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $User = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Products $Products = null;

    #[ORM\OneToMany(mappedBy: 'orders', targetEntity: Payment::class)]
    private Collection $payments;

    public function __construct()
    {
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateOrder(): ?\DateTimeInterface
    {
        return $this->date_order;
    }

    public function setDateOrder(\DateTimeInterface $date_order): self
    {
        $this->date_order = $date_order;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->quantity;
    }

    public function setQuantity(string $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getProducts(): ?Products
    {
        return $this->Products;
    }

    public function setProducts(?Products $Products): self
    {
        $this->Products = $Products;

        return $this;
    }

    /**
     * @return Collection<int, Payment>
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments->add($payment);
            $payment->setOrders($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->removeElement($payment)) {
            // set the owning side to null (unless already changed)
            if ($payment->getOrders() === $this) {
                $payment->setOrders(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminOrdersController.php
<?php

namespace App\Controller;

use App\Entity\Orders;
use App\Form\OrdersType;
use App\Repository\OrdersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/orders')]
class AdminOrdersController extends AbstractController
{
    #[Route('/', name: 'app_admin_orders_index', methods: ['GET'])]
    public function index(OrdersRepository $ordersRepository): Response
    {
        return $this->render('admin_orders/index.html.twig', [
            'orders' => $ordersRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_orders_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OrdersRepository $ordersRepository): Response
    {
        $order = new Orders();
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ordersRepository->save($order, true);

            return $this->redirectToRoute('app_admin_orders_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_orders/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_orders_show', methods: ['GET'])]
    public function show(Orders $order): Response
    {
        return $this->render('admin_orders/show.html.twig', [
            'order' => $order,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_orders_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Orders $order, OrdersRepository $ordersRepository): Response
    {
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ordersRepository->save($order, true);

            return $this->redirectToRoute('app_admin_orders_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_orders/edit.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_orders_delete', methods: ['POST'])]
    public function delete(Request $request, Orders $order, OrdersRepository $ordersRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $ordersRepository->remove($order, true);
        }

        return $this->redirectToRoute('app_admin_orders_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_orders/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_orders_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_orders/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_orders/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Orders{% endblock %}

{% block body %}
    <h1>Edit Orders</h1>

    {{ include('admin_orders/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_orders_index') }}">back to list</a>

    {{ include('admin_orders/_delete_form.html.twig') }}
{% endblock %}

templates/admin_orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders index{% endblock %}

{% block body %}
    <h1>Orders index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_order</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.dateOrder ? order.dateOrder|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ order.quantity }}</td>
                <td>{{ order.price }}</td>
                <td>
                    <a href="{{ path('app_admin_orders_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('app_admin_orders_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_admin_orders_new') }}">Create new</a>
{% endblock %}

templates/admin_orders/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Orders{% endblock %}

{% block body %}
    <h1>Create new Orders</h1>

    {{ include('admin_orders/_form.html.twig') }}

    <a href="{{ path('app_admin_orders_index') }}">back to list</a>
{% endblock %}

templates/admin_orders/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    <h1>Orders</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Date_order</th>
                <td>{{ order.dateOrder ? order.dateOrder|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ order.quantity }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ order.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_orders_index') }}">back to list</a>

    <a href="{{ path('app_admin_orders_edit', {'id': order.id}) }}">edit</a>

    {{ include('admin_orders/_delete_form.html.twig') }}
{% endblock %}